"""momory field assigned migration

Revision ID: db3634f652e8
Revises: a5f340fa06cc
Create Date: 2026-04-11 17:52:25.304639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db3634f652e8'
down_revision: Union[str, Sequence[str], None] = 'a5f340fa06cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_states', sa.Column('memory', sa.Text(), nullable=True))
    op.create_index('idx_conversation_sequence', 'query_states', ['conversation_id', 'sequence_id'], unique=False)
    op.create_foreign_key(None, 'query_states', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_states', type_='foreignkey')
    op.drop_index('idx_conversation_sequence', table_name='query_states')
    op.drop_column('query_states', 'memory')
    # ### end Alembic commands ###
